import com.mycompany.lab5.FormAddParticipant;
import com.mycompany.lab5.FormCongress;
import com.mycompany.lab5.FormCongressAttendees;
import com.mycompany.lab5.FormFindParticipant;
import com.mycompany.lab5.FormIncomeLookup;
import com.mycompany.lab5.FormMonthlyIncome;
import com.mycompany.lab5.FormVotesLookup;

public class Master extends javax.swing.JFrame {

    public Master() {
        initComponents();
        this.setResizable(false);
        
        FormAddParticipant formAddParticipant = new FormAddParticipant();
        FormFindParticipant formFindParticipant = new FormFindParticipant();
        FormCongress formCongress = new FormCongress();
        FormCongressAttendees formCongressAttendees = new FormCongressAttendees();
        FormMonthlyIncome formMonthlyIncome = new FormMonthlyIncome();
        FormIncomeLookup formIncomeLookup = new FormIncomeLookup();
        FormVotesLookup formVotesLookup = new FormVotesLookup();
        
        
        formFindParticipant.getFormCongress(formCongress);
        
        tabbedPane.addTab("Add a new participant", formAddParticipant);
        tabbedPane.addTab("Find participant", formFindParticipant);
        tabbedPane.addTab("Congress manager", formCongress);
        tabbedPane.addTab("Congress attendees", formCongressAttendees);
        tabbedPane.addTab("Votes lookup", formVotesLookup);
        tabbedPane.addTab("Income declaration", formMonthlyIncome);
        tabbedPane.addTab("Income lookup", formIncomeLookup);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Political Party Manager");
        setMinimumSize(new java.awt.Dimension(640, 540));

        tabbedPane.setBackground(new java.awt.Color(51, 204, 255));
        tabbedPane.setMaximumSize(new java.awt.Dimension(640, 640));
        tabbedPane.setMinimumSize(new java.awt.Dimension(640, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void fieldRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldRegionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldRegionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Master().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
