package com.mycompany.lab5;

import java.awt.Color;
import java.awt.Component;
import java.sql.SQLException;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import src.DAOs.DAOParticipants;
import src.Participant;
import src.Regions;
import javax.swing.JOptionPane;

public class FormAddParticipant extends javax.swing.JPanel {

    /**
     * Creates new form AddParticipant
     */
    public FormAddParticipant() {
        initComponents();
        connectToTheDatabase();
        try {
            daoParticipants.create(new Participant("KOSTYA", "BIEKTIN", "OLEKSANDROVYCH", Regions.MYKOLAIV, "1234abcd", 0));
            daoParticipants.create(new Participant("DMITRE", "MARIASH", "IHOROVYCH", Regions.MYKOLAIV, "mfgh7518", 0));
            daoParticipants.create(new Participant("JOHN", "DOE", "MYKOLAYOVYCH", Regions.KHERSON, "n3h57g18", 0));
            daoParticipants.create(new Participant("ROB", "WILLIAMS", "SMYTHOVYCH", Regions.KYIV, "0987gabz", 0));
            daoParticipants.create(new Participant("BOB", "RICHARDSON", "TYHONOVYCH", Regions.CRIMEA, "lpkojihu", 0));
            daoParticipants.create(new Participant("KOSTYA", "BIEKTIN", "OLEKSANDROVYCH", Regions.MYKOLAIV, "1233abcd", 0));
            daoParticipants.create(new Participant("DMITRE", "MARIASH", "IHOROVYCH", Regions.MYKOLAIV, "mfgh1518", 0));
            daoParticipants.create(new Participant("JOHN", "DOE", "MYKOLAYOVYCH", Regions.KHERSON, "n3h57g28", 0));
            daoParticipants.create(new Participant("ROB", "WILLIAMS", "SMYTHOVYCH", Regions.KYIV, "0987gab4", 0));
            daoParticipants.create(new Participant("BOB", "RICHARDSON", "TYHONOVYCH", Regions.CRIMEA, "lpkoji1u", 0));
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

        DocumentListener addFormListener = new DocumentListener() {
            public void insertUpdate(DocumentEvent e) {
                checkFieldsInput();
            }

            public void removeUpdate(DocumentEvent e) {
                checkFieldsInput();
            }

            public void changedUpdate(DocumentEvent e) {
                //Plain text components do not fire these events
            }
        };

        fieldFirstName.getDocument().addDocumentListener(addFormListener);
        fieldLastName.getDocument().addDocumentListener(addFormListener);
        fieldPatronymic.getDocument().addDocumentListener(addFormListener);
        fieldId.getDocument().addDocumentListener(addFormListener);
        
        btnAddNewParticipant.addActionListener(fieldRegion);
    }

    private void connectToTheDatabase() {
        try {
            daoParticipants.setConnection("jdbc:sqlite:E:\\NetBeans Java Projects\\Lab5\\database\\politicalPower.db");
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(this,
                    "Error while connecting to the database!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
    }

    public boolean checkFieldsInput() {
        boolean flag = true;
        
        if (!fieldFirstName.getText().matches("[a-zA-Z]{2,15}")) {
            fieldFirstName.setBackground(Color.red);
        } else {
            fieldFirstName.setBackground(Color.white);
        }

        if (!fieldLastName.getText().matches("[a-zA-Z]{2,15}")) {
            fieldLastName.setBackground(Color.red);
            flag = false;
        } else {
            fieldLastName.setBackground(Color.white);
        }
        
        if (!fieldPatronymic.getText().matches("[a-zA-Z]{6,15}")) {
            fieldPatronymic.setBackground(Color.red);
            flag = false;
        } else {
            fieldPatronymic.setBackground(Color.white);
        }
        
        if (!fieldId.getText().matches("[a-zA-Z0-9]{8}")) {
            fieldId.setBackground(Color.red);
            flag = false;
        } else {
            fieldId.setBackground(Color.white);
        }
        
        return flag;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelInputWarning = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldFirstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fieldLastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fieldPatronymic = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fieldId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fieldRegion = new javax.swing.JComboBox<>();
        btnAddNewParticipant = new javax.swing.JButton();
        btnClearInput = new javax.swing.JButton();
        title = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 204, 255));
        setPreferredSize(new java.awt.Dimension(640, 640));

        labelInputWarning.setForeground(new java.awt.Color(255, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("First Name");

        fieldFirstName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fieldFirstName.setName("firstName"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Last Name");

        fieldLastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fieldLastName.setName("lastName"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Patronymic");

        fieldPatronymic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fieldPatronymic.setName("fieldPatronymic"); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("ID");

        fieldId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fieldId.setName("participantId"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Region");

        fieldRegion.setBackground(java.awt.Color.cyan);
        fieldRegion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fieldRegion.setModel(new DefaultComboBoxModel(getRegionsNames()));

        btnAddNewParticipant.setBackground(java.awt.Color.cyan);
        btnAddNewParticipant.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddNewParticipant.setText("Add");
        btnAddNewParticipant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddNewParticipantMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddNewParticipantMouseExited(evt);
            }
        });
        btnAddNewParticipant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewParticipantActionPerformed(evt);
            }
        });

        btnClearInput.setBackground(java.awt.Color.cyan);
        btnClearInput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClearInput.setText("Clear");
        btnClearInput.setActionCommand("");
        btnClearInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearInputMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearInputMouseExited(evt);
            }
        });
        btnClearInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearInputActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        title.setText("Enter personal information of the new participant");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(fieldPatronymic)
                                        .addComponent(jLabel8)
                                        .addComponent(fieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fieldRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAddNewParticipant, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnClearInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelInputWarning)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(title)))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {fieldFirstName, fieldId, fieldLastName, fieldPatronymic, fieldRegion});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddNewParticipant, btnClearInput});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(labelInputWarning)
                .addGap(81, 81, 81)
                .addComponent(title)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldPatronymic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNewParticipant)
                    .addComponent(btnClearInput))
                .addGap(200, 200, 200))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearInputActionPerformed
        fieldFirstName.setText("");
        fieldLastName.setText("");
        fieldPatronymic.setText("");
        fieldId.setText("");
    }//GEN-LAST:event_btnClearInputActionPerformed

    private void btnAddNewParticipantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewParticipantActionPerformed
        if (!checkFieldsInput()) {
            JOptionPane.showMessageDialog(this,
                    "Check input!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String firstName = fieldFirstName.getText().toUpperCase();
        String lastName = fieldLastName.getText().toUpperCase();
        String patronymic = fieldPatronymic.getText().toUpperCase();
        Regions region = Regions.valueOf((String) fieldRegion.getSelectedItem());
        String id = fieldId.getText();

        Participant participant = new Participant(firstName, lastName, patronymic, region, id, 0);
        try {
            daoParticipants.create(participant);
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(this,
                    "Error while adding new database record!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddNewParticipantActionPerformed
    
    private void btnClearInputMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearInputMouseEntered
        evt.getComponent().setBackground(Color.YELLOW);
    }//GEN-LAST:event_btnClearInputMouseEntered

    private void btnClearInputMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearInputMouseExited
        evt.getComponent().setBackground(Color.CYAN);
    }//GEN-LAST:event_btnClearInputMouseExited

    private void btnAddNewParticipantMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewParticipantMouseEntered
        evt.getComponent().setBackground(Color.YELLOW);
    }//GEN-LAST:event_btnAddNewParticipantMouseEntered

    private void btnAddNewParticipantMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewParticipantMouseExited
        evt.getComponent().setBackground(Color.CYAN);
    }//GEN-LAST:event_btnAddNewParticipantMouseExited

    private Object[] getRegionsNames() {
        return Stream.of(Regions.values())
                .map(Enum::toString)
                .collect(Collectors.toList())
                .toArray();
    }

    private DAOParticipants daoParticipants = new DAOParticipants();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewParticipant;
    private javax.swing.JButton btnClearInput;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldId;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldPatronymic;
    private javax.swing.JComboBox<String> fieldRegion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel labelInputWarning;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
